export interface Web2Tool {
  id: string;
  name: string;
  url: string;
  description: string;
  descriptionEn: string;
  category: string;
  categoryEn: string;
  categoryKey: string;
  color: string;
}

export const web2Categories = [
  { key: "all", tr: "Tümü", en: "All" },
  { key: "graphic", tr: "Görsel Tasarım & Poster", en: "Visual Design & Poster" },
  { key: "collaborative", tr: "İşbirlikçi Panolar", en: "Collaborative Boards" },
  { key: "presentation", tr: "Sunum & Belge", en: "Presentation & Document" },
  { key: "survey", tr: "Anket & Oyunlaştırma", en: "Survey & Gamification" },
  { key: "story", tr: "Dijital Hikaye", en: "Digital Storytelling" },
  { key: "video", tr: "Video & Multimedya", en: "Video & Multimedia" },
  { key: "mindmap", tr: "Zihin Haritası", en: "Mind Mapping" },
  { key: "avatar", tr: "Avatar & Karakter", en: "Avatar & Character" },
  { key: "meeting", tr: "Sanal Toplantı", en: "Virtual Meeting" },
  { key: "interactive", tr: "İnteraktif Araçlar", en: "Interactive Tools" },
  { key: "custom", tr: "Özel Uygulamalar", en: "Special Apps" },
];

export const web2Tools: Web2Tool[] = [
  // 1. Görsel Tasarım & Poster
  {
    id: "canva",
    name: "Canva",
    url: "https://www.canva.com/",
    description: "Projeye özel logo, poster, afiş, infografik, sunum ve kısa video hazırlamak için kullanılır. Öğrenciler görsel materyaller üretirken tasarım becerilerini geliştirir.",
    descriptionEn: "Used to create project logos, posters, infographics, presentations, and short videos. Develops design skills.",
    category: "Görsel Tasarım & Poster",
    categoryEn: "Visual Design & Poster",
    categoryKey: "graphic",
    color: "from-cyan-500 to-blue-500",
  },
  {
    id: "postermywall",
    name: "PosterMyWall",
    url: "https://www.postermywall.com/",
    description: "Özellikle poster ve broşür tasarlamak için tercih edilir. Şablon kütüphanesi oldukça zengindir.",
    descriptionEn: "Preferred for designing posters and brochures with rich template libraries.",
    category: "Görsel Tasarım & Poster",
    categoryEn: "Visual Design & Poster",
    categoryKey: "graphic",
    color: "from-indigo-500 to-purple-500",
  },

  // 2. İşbirlikçi Panolar & Paylaşım
  {
    id: "padlet",
    name: "Padlet",
    url: "https://padlet.com/",
    description: "Öğrencilerin fikirlerini, fotoğraflarını ve videolarını tek bir dijital pano üzerinde paylaşması için kullanılır.",
    descriptionEn: "Used for students to share ideas, photos, and videos on a single collaborative digital board.",
    category: "İşbirlikçi Panolar",
    categoryEn: "Collaborative Boards",
    categoryKey: "collaborative",
    color: "from-pink-500 to-rose-500",
  },
  {
    id: "wakelet",
    name: "Wakelet",
    url: "https://wakelet.com/",
    description: "Farklı kaynaklardan (video, makale, link, görsel) toplanan içerikleri düzenli bir şekilde bir araya getirmek için kullanılır.",
    descriptionEn: "Used to curate and organize content collected from various sources into structured collections.",
    category: "İşbirlikçi Panolar",
    categoryEn: "Collaborative Boards",
    categoryKey: "collaborative",
    color: "from-blue-500 to-cyan-500",
  },

  // 3. Sunum & Belge Oluşturma
  {
    id: "google-slides",
    name: "Google Slides",
    url: "https://slides.google.com/",
    description: "Farklı ülkelerden öğrenciler aynı anda ortak sunum hazırlayabilir.",
    descriptionEn: "Allows students from different partner countries to collaborate on joint presentations simultaneously.",
    category: "Sunum & Belge",
    categoryEn: "Presentation & Document",
    categoryKey: "presentation",
    color: "from-yellow-500 to-orange-500",
  },
  {
    id: "google-docs",
    name: "Google Docs",
    url: "https://docs.google.com/",
    description: "Ortak metin yazma, proje planı oluşturma, hikaye yazma ve rapor hazırlama için kullanılır.",
    descriptionEn: "Used for joint text writing, project planning, storytelling, and real-time document editing.",
    category: "Sunum & Belge",
    categoryEn: "Presentation & Document",
    categoryKey: "presentation",
    color: "from-blue-500 to-indigo-500",
  },
  {
    id: "genially",
    name: "Genially",
    url: "https://genially.com/",
    description: "İnteraktif sunumlar, posterler, escape room'lar ve gamification içerikleri oluşturmak için kullanılır.",
    descriptionEn: "Used to create interactive presentations, posters, escape rooms, and gamified content.",
    category: "Sunum & Belge",
    categoryEn: "Presentation & Document",
    categoryKey: "presentation",
    color: "from-blue-600 to-violet-600",
  },
  {
    id: "prezi",
    name: "Prezi",
    url: "https://prezi.com/",
    description: "Dinamik ve akıcı sunumlar hazırlamak için tercih edilir.",
    descriptionEn: "Preferred for designing dynamic, non-linear animated presentations.",
    category: "Sunum & Belge",
    categoryEn: "Presentation & Document",
    categoryKey: "presentation",
    color: "from-sky-500 to-blue-600",
  },

  // 4. Anket & Oyunlaştırma
  {
    id: "kahoot",
    name: "Kahoot!",
    url: "https://kahoot.com/",
    description: "Konuyla ilgili bilgi ölçmek, motivasyonu artırmak ve eğlenceli yarışmalar düzenlemek için kullanılır.",
    descriptionEn: "Used to assess student knowledge, boost engagement, and host interactive quizzes.",
    category: "Anket & Oyunlaştırma",
    categoryEn: "Survey & Gamification",
    categoryKey: "survey",
    color: "from-purple-500 to-indigo-600",
  },
  {
    id: "google-forms",
    name: "Google Forms",
    url: "https://forms.google.com/",
    description: "Proje başlangıcında ihtiyaç analizi, süreç değerlendirmesi ve son değerlendirme anketleri oluşturmak için kullanılır.",
    descriptionEn: "Used to create surveys for initial needs analysis, evaluation, and feedback.",
    category: "Anket & Oyunlaştırma",
    categoryEn: "Survey & Gamification",
    categoryKey: "survey",
    color: "from-purple-500 to-fuchsia-500",
  },
  {
    id: "mentimeter",
    name: "Mentimeter",
    url: "https://www.mentimeter.com/",
    description: "Canlı oylama, kelime bulutu ve beyin fırtınası yapmak için kullanılır.",
    descriptionEn: "Used to build live polls, word clouds, and interactive feedback sessions during meetings.",
    category: "Anket & Oyunlaştırma",
    categoryEn: "Survey & Gamification",
    categoryKey: "survey",
    color: "from-teal-500 to-emerald-500",
  },
  {
    id: "wordwall",
    name: "Wordwall",
    url: "https://wordwall.net/",
    description: "Kelime etkinlikleri, eşleştirme oyunları, quiz ve sıralama etkinlikleri hazırlamak için kullanılır.",
    descriptionEn: "Used to create custom learning activities, matching games, quizzes, and vocabulary cards.",
    category: "Anket & Oyunlaştırma",
    categoryEn: "Survey & Gamification",
    categoryKey: "survey",
    color: "from-blue-500 to-sky-500",
  },
  {
    id: "quizizz",
    name: "Quizizz",
    url: "https://quizizz.com/",
    description: "Kahoot'a alternatif quiz platformudur. Öğrenciler kendi hızlarında çözebilir.",
    descriptionEn: "Self-paced gamified quiz platform alternative to Kahoot.",
    category: "Anket & Oyunlaştırma",
    categoryEn: "Survey & Gamification",
    categoryKey: "survey",
    color: "from-purple-500 to-pink-500",
  },

  // 5. Dijital Hikaye
  {
    id: "storyjumper",
    name: "StoryJumper",
    url: "https://www.storyjumper.com/",
    description: "Öğrencilerin kendi yazdığı hikayeleri resimlerle birleştirip dijital kitap haline getirmesi için kullanılır.",
    descriptionEn: "Used for students to write, illustrate, and publish digital storybooks.",
    category: "Dijital Hikaye",
    categoryEn: "Digital Storytelling",
    categoryKey: "story",
    color: "from-orange-500 to-amber-500",
  },
  {
    id: "book-creator",
    name: "Book Creator",
    url: "https://bookcreator.com/",
    description: "İnteraktif e-kitaplar, dijital dergiler ve portfolyo oluşturmak için kullanılır. Ses kaydı ve video eklenebilir.",
    descriptionEn: "Ideal for creating collaborative digital ebooks, interactive magazines, or student portfolios.",
    category: "Dijital Hikaye",
    categoryEn: "Digital Storytelling",
    categoryKey: "story",
    color: "from-blue-400 to-blue-600",
  },

  // 6. Video & Multimedya
  {
    id: "renderforest",
    name: "Renderforest",
    url: "https://www.renderforest.com/",
    description: "Proje tanıtım videosu, animasyonlu logo ve kısa filmler hazırlamak için kullanılır.",
    descriptionEn: "Used to create project intro videos, animated logos, and short films.",
    category: "Video & Multimedya",
    categoryEn: "Video & Multimedia",
    categoryKey: "video",
    color: "from-emerald-500 to-teal-500",
  },
  {
    id: "powtoon",
    name: "Powtoon",
    url: "https://www.powtoon.com/",
    description: "Animasyonlu sunum ve açıklayıcı videolar oluşturmak için tercih edilir.",
    descriptionEn: "Preferred for creating animated presentations and explanatory videos.",
    category: "Video & Multimedya",
    categoryEn: "Video & Multimedia",
    categoryKey: "video",
    color: "from-cyan-500 to-blue-500",
  },
  {
    id: "animoto",
    name: "Animoto",
    url: "https://animoto.com/",
    description: "Fotoğraf ve videolardan kısa tanıtım filmleri ve kolaj videolar hazırlamak için kullanılır.",
    descriptionEn: "Used to produce video slideshows and photo collages easily.",
    category: "Video & Multimedya",
    categoryEn: "Video & Multimedia",
    categoryKey: "video",
    color: "from-rose-500 to-pink-500",
  },

  // 7. Zihin Haritası
  {
    id: "mindmeister",
    name: "MindMeister",
    url: "https://www.mindmeister.com/",
    description: "Proje planı oluşturma, kavramları organize etme ve ortak zihin haritası hazırlama için kullanılır.",
    descriptionEn: "Used to organize concepts, plan project steps, and build collaborative mind maps.",
    category: "Zihin Haritası",
    categoryEn: "Mind Mapping",
    categoryKey: "mindmap",
    color: "from-blue-500 to-indigo-500",
  },
  {
    id: "popplet",
    name: "Popplet",
    url: "https://popplet.com/",
    description: "Basit ve görsel kavram haritaları oluşturmak için tercih edilir. İlkokul seviyesinde sık kullanılır.",
    descriptionEn: "Simple and visual concept mapping tool ideal for younger students.",
    category: "Zihin Haritası",
    categoryEn: "Mind Mapping",
    categoryKey: "mindmap",
    color: "from-pink-500 to-rose-500",
  },

  // 8. Avatar & Karakter
  {
    id: "voki",
    name: "Voki",
    url: "https://www.voki.com/",
    description: "Öğrencilerin kendi avatarlarını oluşturup konuşmasını sağlamak için kullanılır. Rol yapma etkinliklerinde işe yarar.",
    descriptionEn: "Allows students to create speaking avatars for introductions and role-playing activities.",
    category: "Avatar & Karakter",
    categoryEn: "Avatar & Character",
    categoryKey: "avatar",
    color: "from-violet-500 to-purple-500",
  },
  {
    id: "chatterpix",
    name: "Chatterpix",
    url: "https://www.duckduckgo.com/?q=chatterpix",
    description: "Fotoğraflara ses ekleyerek 'konuşan resimler' oluşturmak için kullanılır. (Mobil Uygulama)",
    descriptionEn: "Mobile app used to make photos speak by adding recorded voiceovers.",
    category: "Avatar & Karakter",
    categoryEn: "Avatar & Character",
    categoryKey: "avatar",
    color: "from-orange-500 to-red-500",
  },

  // 9. Sanal Toplantı
  {
    id: "zoom",
    name: "Zoom",
    url: "https://zoom.us/",
    description: "Sanal toplantı, ortak sunum ve atölye çalışmaları için kullanılır. Breakout odaları sunar.",
    descriptionEn: "Used for online partner teacher meetings and live student video workshops.",
    category: "Sanal Toplantı",
    categoryEn: "Virtual Meeting",
    categoryKey: "meeting",
    color: "from-blue-500 to-blue-600",
  },
  {
    id: "google-meet",
    name: "Google Meet",
    url: "https://meet.google.com/",
    description: "Google araçlarıyla entegre çalıştığı için tercih edilir. Basit ve erişimi kolaydır.",
    descriptionEn: "Accessible video conferencing integrated with Google Workspace tools.",
    category: "Sanal Toplantı",
    categoryEn: "Virtual Meeting",
    categoryKey: "meeting",
    color: "from-teal-500 to-green-500",
  },

  // 10. İnteraktif Araçlar
  {
    id: "thinglink",
    name: "Thinglink",
    url: "https://www.thinglink.com/",
    description: "Fotoğraf veya videolara tıklanabilir noktalar ekleyerek interaktif materyal oluşturmak için kullanılır.",
    descriptionEn: "Used to add clickable hotspots, text, and media to photos and 360 images.",
    category: "İnteraktif Araçlar",
    categoryEn: "Interactive Tools",
    categoryKey: "interactive",
    color: "from-cyan-500 to-teal-500",
  },
  {
    id: "learningapps",
    name: "LearningApps",
    url: "https://learningapps.org/",
    description: "Hazır şablonlarla interaktif öğrenme aktiviteleri oluşturmak için kullanılır.",
    descriptionEn: "Free building blocks for interactive learning modules and exercises.",
    category: "İnteraktif Araçlar",
    categoryEn: "Interactive Tools",
    categoryKey: "interactive",
    color: "from-yellow-500 to-orange-500",
  },

  // 11. Özel Uygulamalar (Self-Hosted Apps)
  {
    id: "classquiz",
    name: "ClassQuiz",
    url: "https://quiz.etwinasistan.com",
    description: "Kahoot benzeri sınıf içi test ve interaktif quiz yarışmaları düzenlemek için güvenli platformumuz.",
    descriptionEn: "Our secure self-hosted quiz platform for hosting interactive class competitions.",
    category: "Özel Uygulamalar",
    categoryEn: "Special Apps",
    categoryKey: "custom",
    color: "from-indigo-500 to-purple-600",
  },
  {
    id: "etherpad",
    name: "Etherpad",
    url: "https://ortak.etwinasistan.com",
    description: "Öğrencilerin aynı anda canlı olarak metin ve hikaye yazabileceği ortak çalışma alanımız.",
    descriptionEn: "Real-time collaborative text editor for students to write stories together.",
    category: "Özel Uygulamalar",
    categoryEn: "Special Apps",
    categoryKey: "custom",
    color: "from-emerald-500 to-teal-600",
  },
  {
    id: "answer",
    name: "Answer",
    url: "https://soru.etwinasistan.com",
    description: "Öğretmenlerin ve öğrencilerin soru sorup cevaplayabileceği proje soru-cevap platformumuz.",
    descriptionEn: "Q&A community platform for teachers and students to exchange knowledge.",
    category: "Özel Uygulamalar",
    categoryEn: "Special Apps",
    categoryKey: "custom",
    color: "from-orange-500 to-red-500",
  },
  {
    id: "stirling-pdf",
    name: "Stirling PDF",
    url: "https://pdf.etwinasistan.com",
    description: "PDF belgelerinizi birleştirin, bölün veya düzenleyin. %100 güvenli kendi sunucumuzda.",
    descriptionEn: "Self-hosted PDF manipulation tools: merge, split, compress, and edit PDFs safely.",
    category: "Özel Uygulamalar",
    categoryEn: "Special Apps",
    categoryKey: "custom",
    color: "from-rose-500 to-pink-600",
  },
  {
    id: "heyform",
    name: "HeyForm",
    url: "https://anket.etwinasistan.com",
    description: "Proje öncesi, süreci ve sonrası için detaylı anketler ve formlar hazırlayın.",
    descriptionEn: "Build engaging online forms, questionnaires, and survey forms.",
    category: "Özel Uygulamalar",
    categoryEn: "Special Apps",
    categoryKey: "custom",
    color: "from-blue-400 to-indigo-500",
  },
  {
    id: "bookstack",
    name: "BookStack",
    url: "https://kutuphane.etwinasistan.com",
    description: "Proje dökümantasyonu, e-kitaplar ve kuralları tutabileceğiniz kütüphane sistemimiz.",
    descriptionEn: "Organized documentation platform to store ebooks and project guidelines.",
    category: "Özel Uygulamalar",
    categoryEn: "Special Apps",
    categoryKey: "custom",
    color: "from-amber-500 to-orange-600",
  },
  {
    id: "trilium",
    name: "Trilium Notes",
    url: "https://not.etwinasistan.com",
    description: "Kişisel ve işbirlikçi notlar almak, proje günlükleri tutmak için not alma uygulaması.",
    descriptionEn: "Hierarchical note-taking application for building project knowledge bases.",
    category: "Özel Uygulamalar",
    categoryEn: "Special Apps",
    categoryKey: "custom",
    color: "from-teal-500 to-emerald-600",
  },
  {
    id: "wbo",
    name: "WBO (Beyaz Tahta)",
    url: "https://pano.etwinasistan.com",
    description: "Gerçek zamanlı ortak çalışma, çizim yapma ve fikir geliştirme için beyaz tahta aracımız.",
    descriptionEn: "Online collaborative whiteboard for real-time drawing and brainstorming.",
    category: "Özel Uygulamalar",
    categoryEn: "Special Apps",
    categoryKey: "custom",
    color: "from-fuchsia-500 to-purple-600",
  },
  {
    id: "penpot",
    name: "Penpot",
    url: "https://tasarim.etwinasistan.com",
    description: "Açık kaynaklı tasarım ve prototip oluşturma aracı. Görsel materyal tasarlayın.",
    descriptionEn: "Open-source design and prototyping tool for creating visual graphics together.",
    category: "Özel Uygulamalar",
    categoryEn: "Special Apps",
    categoryKey: "custom",
    color: "from-cyan-500 to-blue-600",
  },
];
